const nicaragua_cities = [
    {
      Estado: "Boaco",
      Ciudades: [
        "Boaco",
        "Camoapa",
        "Santa Lucía",
        "San José de los Remates",
        "San Lorenzo",
        "Teustepe",
      ],
    },
    {
      Estado: "Carazo",
      Ciudades: [
        "Jinotepe",
        "Diriamba",
        "Dolores",
        "El Rosario",
        "La Conquista",
        "La Paz de Carazo",
        "San Marcos",
        "Santa Teresa",
      ],
    },
    {
      Estado: "Chinandega",
      Ciudades: [
        "Chinandega",
        "Chichigalpa",
        "Corinto",
        "El Realejo",
        "El Viejo",
        "Posoltega",
        "Puerto Morazán",
        "Somotillo",
        "Villa Nueva",
        "Santo Tomás del Norte",
        "Cinco Pinos",
        "San Pedro del Norte",
      ],
    },
    {
      Estado: "Chontales",
      Ciudades: [
        "Juigalpa",
        "Acoyapa",
        "Comalapa",
        "Cuapa",
        "El Coral",
        "La Libertad",
        "San Francisco de Cuapa",
        "San Pedro de Lóvago",
        "Santo Domingo",
        "Santo Tomás",
        "Villa Sandino",
      ],
    },
    {
      Estado: "Estelí",
      Ciudades: [
        "Estelí",
        "Condega",
        "La Trinidad",
        "Pueblo Nuevo",
        "San Juan de Limay",
        "San Nicolás",
      ],
    },
    {
      Estado: "Granada",
      Ciudades: ["Granada", "Diriá", "Diriomo", "Nandaime"],
    },
    {
      Estado: "Jinotega",
      Ciudades: [
        "Jinotega",
        "El Cuá",
        "La Concordia",
        "San José de Bocay",
        "San Rafael del Norte",
        "San Sebastián de Yalí",
        "Santa María de Pantasma",
        "Wiwilí de Jinotega",
      ],
    },
    {
      Estado: "León",
      Ciudades: [
        "León",
        "Achuapa",
        "El Jicaral",
        "El Sauce",
        "La Paz Centro",
        "Quezalguaque",
        "Santa Rosa del Peñón",
        "Telica",
        "Nagarote",
        "Malpaisillo",
      ],
    },
    {
      Estado: "Madriz",
      Ciudades: [
        "Somoto",
        "Las Sabanas",
        "Palacagüina",
        "San José de Cusmapa",
        "San Juan de Río Coco",
        "San Lucas",
        "Telpaneca",
        "Totogalpa",
        "Yalagüina",
      ],
    },
    {
      Estado: "Managua",
      Ciudades: [
        "Managua",
        "Ciudad Sandino",
        "El Crucero",
        "Mateare",
        "San Francisco Libre",
        "San Rafael del Sur",
        "Ticuantepe",
        "Tipitapa",
        "Villa El Carmen",
      ],
    },
    {
      Estado: "Masaya",
      Ciudades: [
        "Masaya",
        "Catarina",
        "La Concepción",
        "Masatepe",
        "Nandasmo",
        "Nindirí",
        "Niquinohomo",
        "San Juan de Oriente",
        "Tisma",
      ],
    },
    {
      Estado: "Matagalpa",
      Ciudades: [
        "Matagalpa",
        "Ciudad Darío",
        "El Tuma - La Dalia",
        "Esquipulas",
        "Matiguás",
        "Muy Muy",
        "Rancho Grande",
        "Río Blanco",
        "San Dionisio",
        "San Isidro",
        "Sébaco",
        "Terrabona",
      ],
    },
    {
      Estado: "Nueva Segovia",
      Ciudades: [
        "Ocotal",
        "Ciudad Antigua",
        "Dipilto",
        "El Jícaro",
        "Jalapa",
        "Macuelizo",
        "Mozonte",
        "Murra",
        "Quilalí",
        "San Fernando",
        "Santa María",
      ],
    },
    {
      Estado: "Rivas",
      Ciudades: [
        "Rivas",
        "Altagracia",
        "Belén",
        "Buenos Aires",
        "Cárdenas",
        "Moyogalpa",
        "Potosí",
        "San Jorge",
        "San Juan del Sur",
        "Tola",
      ],
    },
    {
      Estado: "Río San Juan",
      Ciudades: [
        "San Carlos",
        "El Almendro",
        "El Castillo",
        "Morrito",
        "San Juan de Nicaragua",
        "San Miguelito",
      ],
    }
  ];
  export default nicaragua_cities;