const panama_cities = [
    {
        Estado: "Bocas del Toro",
        Ciudades: [
            "Bocas del Toro",
            "Changuinola",
            "Almirante",
            "Chiriquí Grande",
            "Punta Peña",
            "Bastimentos",
            "Boquete",
            "David",
        ],
    },
    {
        Estado: "Coclé",
        Ciudades: [
            "Aguadulce",
            "Antón",
            "Penonomé",
            "La Pintada",
            "Nata",
            "Ocu",
            "San Juan de Dios",
            "El Valle de Antón",
        ],
    },
    {
        Estado: "Colón",
        Ciudades: [
            "Colón",
            "Cristóbal",
            "Portobelo",
            "Sabanitas",
            "Chagres",
            "Santa Isabel",
            "Nuevo Colón",
            "Gamboa",
        ],
    },
    {
        Estado: "Darién",
        Ciudades: [
            "La Palma",
            "Santa Fe",
            "Metetí",
            "Yaviza",
            "El Real",
            "Cana",
            "Paya",
        ],
    },
    {
        Estado: "Herrera",
        Ciudades: [
            "Chitré",
            "Las Minas",
            "Parita",
            "La Villa",
            "Pesé",
            "Ocú",
            "Santa María",
            "El Bambito",
        ],
    },
    {
        Estado: "Panamá",
        Ciudades: [
            "Ciudad de Panamá",
            "San Miguelito",
            "Balboa",
            "Ancon",
            "Panamá Viejo",
            "Albrook",
            "Juan Díaz",
            "Bella Vista",
            "El Cangrejo",
            "Calidonia",
        ],
    },
    {
        Estado: "Panamá Oeste",
        Ciudades: [
            "Arraiján",
            "La Chorrera",
            "Capira",
            "Chame",
            "San Carlos",
            "La Laguna",
            "Sora",
            "Puerto Caimito",
        ],
    },
    {
        Estado: "Veraguas",
        Ciudades: [
            "Santiago",
            "Soná",
            "Las Palmas",
            "Río de Jesús",
            "La Villa de Los Santos",
            "Montijo",
            "San Francisco",
        ],
    },
    {
        Estado: "Guna Yala",
        Ciudades: [
            "El Porvenir",
            "Narganá",
            "Corazón de Jesús",
            "Ustupu",
            "Cabo de la Vela",
            "Wargandí",
        ],
    },
    {
        Estado: "Ngäbe-Buglé",
        Ciudades: [
            "Río de Jesús",
            "Nole Düima",
            "Cerro Iglesia",
            "Kankintú",
            "Santa Catalina",
            "Soloy",
            "Piriatí",
        ],
    },
    {
        Estado: "Comarca Emberá",
        Ciudades: [
            "Nidito",
            "Cémaco",
            "Piriatí",
            "Balsa",
        ],
    },
    {
        Estado: "Comarca Wounaan",
        Ciudades: [
            "Boca de Cupe",
            "Yaviza",
            "Paya",
            "Divalá",
        ],
    },
    {
        Estado: "Comarca de Guna Yala",
        Ciudades: [
            "Cemaco",
            "Narganá",
            "Yandub",
            "Ustupu",
            "Bocas del Toro",
        ],
    },
    {
        Estado: "Región Especial de San Miguelito",
        Ciudades: [
            "San Miguelito",
            "Los Andes",
            "Villa Lucre",
            "Panamá Viejo",
            "Brisas del Golf",
            "Santa Librada",
        ],
    },
];

export default panama_cities;
