const paraguay_cities = [
  {
    Estado: "Alto Paraguay",
    Ciudades: [
      "Fuerte Olimpo",
      "Puerto Casado",
      "Puerto Sastre",
      "Puerto La Esperanza",
    ],
  },
  {
    Estado: "Alto Paraná",
    Ciudades: [
      "Ciudad del Este",
      "Presidente Franco",
      "Hernandarias",
      "Minga Guazú",
      "Santa Rita",
      "Juan León Mallorquín",
      "Santa Rosa del Monday",
      "Iruña", 
      "Naranjal",
      "Los Cedrales",
      "San Alberto",
    ],
  },
  {
    Estado: "Amambay",
    Ciudades: ["Pedro Juan Caballero", "Bella Vista Norte", "Zanja Pytã"],
  },
  {
    Estado: "Boquerón",
    Ciudades: ["Filadelfia", "Loma Plata", "Mariscal Estigarribia", "Neuland"],
  },
  {
    Estado: "Caaguazú",
    Ciudades: [
      "Coronel Oviedo",
      "Caaguazú",
      "Caapucú",
      "Doctor Cecilio Báez",
      "Doctor Juan Eulogio Estigarribia",
      "J. Eulogio Estigarribia",
      "José Domingo Ocampos",
      "La Pastora",
      "Repatriación",
      "Raúl Arsenio Oviedo",
      "San José de los Arroyos",
      "Tembiaporá",
    ],
  },
  {
    Estado: "Caazapá",
    Ciudades: [
      "Caazapá",
      "Abaí",
      "Buena Vista",
      "Doctor Moisés Bertoni",
      "Fulgencio Yegros",
      "General Higinio Morínigo",
      "Maciel",
      "San Juan Nepomuceno",
      "Tavai",
      "Yuty",
    ],
  },
  {
    Estado: "Canindeyú",
    Ciudades: [
      "Salto del Guairá",
      "Curuguaty",
      "Ybyrarobana",
      "Yasy Cañy",
      "La Paloma",
      "Katueté",
      "Corpus Christi",
      "Villa Ygatimí",
      "Nueva Esperanza",
    ],
  },
  {
    Estado: "Central",
    Ciudades: [
      "Areguá",
      "Capiatá",
      "Fernando de la Mora",
      "Guarambaré",
      "Itá",
      "Itauguá",
      "J. Augusto Saldívar",
      "Lambaré",
      "Limpio",
      "Mariano Roque Alonso",
      "Nueva Italia",
      "Ñemby",
      "San Antonio",
      "San Lorenzo",
      "Villa Elisa",
      "Villeta",
      "Ypacaraí",
      "Ypané",
    ],
  },
  {
    Estado: "Concepción",
    Ciudades: [
      "Concepción",
      "Horqueta",
      "Yby Yaú",
      "Loreto",
      "Belén",
      "San Alfredo",
      "Sargento José Félix López",
      "San Carlos del Apa",
    ],
  },
  {
    Estado: "Cordillera",
    Ciudades: [
      "Caacupé",
      "Altos",
      "Arroyos y Esteros",
      "Atirá",
      "Caraguatay",
      "Emboscada",
      "Eusebio Ayala",
      "Isla Pucú",
      "Itacurubí de la Cordillera",
      "Juan de Mena",
      "Loma Grande",
      "Mbocayaty del Yhaguy",
      "Nueva Colombia",
      "Piribebuy",
      "Primero de Marzo",
      "San Bernardino",
      "Santa Elena",
      "Tobatí",
      "Valenzuela",
    ],
  },
  {
    Estado: "Asunción",
    Ciudades: [
      "Asunción",
    ],
  },
  {
    Estado: "Guairá",
    Ciudades: [
      "Villarrica",
      "Borja",
      "Coronel Martínez",
      "Doctor Bottrell",
      "Félix Pérez Cardozo",
      "General Eugenio A. Garay",
      "Iturbe",
      "Independencia",
      "José Fassardi",
      "Maciel",
      "Mbocayaty",
      "Natalicio Talavera",
      "Paso Yobai",
      "San Salvador",
      "Yataity",
    ],
  },
  {
    Estado: "Itapúa",
    Ciudades: [
      "Encarnación",
      "Alto Verá",
      "Bella Vista",
      "Cambyretá",
      "Capitán Meza",
      "Capitán Miranda",
      "Carlos Antonio López",
      "Coronel Bogado",
      "Edelira",
      "Fram",
      "General Artigas",
      "General Delgado",
      "Hohenau",
      "Jesús",
      "La Paz",
      "Natalio",
      "Nueva Alborada",
      "Obligado",
      "Pirapó",
      "San Cosme y Damián",
      "San Juan del Paraná",
      "San Pedro del Paraná",
      "San Rafael del Paraná",
      "Tomás Romero Pereira",
      "Trinidad",
      "Yatytay",
    ],
  },
  {
    Estado: "Misiones",
    Ciudades: [
      "San Juan Bautista",
      "Ayolas",
      "San Ignacio",
      "San Miguel",
      "San Patricio",
      "Santa María",
      "Santa Rosa",
      "Santiago",
      "Villa Florida",
      "Yabebyry",
    ],
  },
  {
    Estado: "Ñeembucú",
    Ciudades: [
      "Pilar",
      "Alberdi",
      "Cerrito",
      "Desmochados",
      "General José Eduvigis Díaz",
      "Guazú Cuá",
      "Humaitá",
      "Isla Umbú",
      "Laureles",
      "Paso de Patria",
      "San Juan Bautista de Ñeembucú",
      "Tacuaras",
      "Villa Franca",
      "Villa Oliva",
    ],
  },
  {
    Estado: "Paraguarí",
    Ciudades: [
      "Paraguarí",
      "Acahay",
      "Caapucú",
      "Carapeguá",
      "Escobar",
      "Gral. Bernardino Caballero",
      "La Colmena",
      "Mbuyapey",
      "Pirayú",
      "Quiindy",
      "Quyquyhó",
      "San Roque González de Santa Cruz",
      "Sapucai",
      "Tebicuarymí",
      "Yaguarón",
      "Ybycuí",
    ],
  },
  {
    Estado: "Presidente Hayes",
    Ciudades: [
      "Villa Hayes",
      "Benjamín Aceval",
      "José Falcón",
      "Nanawa",
      "Puerto Pinasco",
      "Teniente Esteban Martínez",
      "Villa del Rosario",
    ],
  },
  {
    Estado: "San Pedro",
    Ciudades: [
      "San Pedro de Ycuamandiyú",
      "Antequera",
      "Choré",
      "General Elizardo Aquino",
      "Guayaibí",
      "Itacurubí del Rosario",
      "Lima",
      "Nueva Germania",
      "San Estanislao",
      "Santa Rosa del Aguaray",
      "Tacuatí",
      "Unión",
      "Yataity del Norte",
      "Yrybucua",
    ],
  },
];

export default paraguay_cities;
