const uruguay_cities = [
    {
      Estado: "Artigas",
      Ciudades: [
        "Artigas",
        "Bella Unión",
        "Tomás Gomensoro",
        "Bernabé Rivera",
        "Severino",
        "Topador",
        "Pintadito",
        "Paso Campamento",
        "Baltasar Brum",
      ],
    },
    {
      Estado: "Canelones",
      Ciudades: [
        "Canelones",
        "Las Piedras",
        "Pando",
        "Santa Lucía",
        "Progreso",
        "La Paz",
        "San Ramón",
        "Sauce",
        "Toledo",
        "Barros Blancos",
        "Empalme Olmos",
        "Parque del Plata",
        "Atlántida",
        "Ciudad de la Costa",
        "La Floresta",
        "Paso Carrasco",
      ],
    },
    {
      Estado: "Cerro Largo",
      Ciudades: [
        "Melo",
        "Río Branco",
        "Fraile Muerto",
        "Tupambaé",
        "Aceguá",
        "Arbolito",
        "Isidoro Noblía",
        "Plácido Rosas",
        "Centurión",
        "Lago Merín",
        "Quebracho",
        "Cuchilla de Silvera",
      ],
    },
    {
      Estado: "Colonia",
      Ciudades: [
        "Colonia del Sacramento",
        "Nueva Helvecia",
        "Carmelo",
        "Juan Lacaze",
        "Rosario",
        "Tarariras",
        "Ombúes de Lavalle",
        "Nueva Palmira",
        "Colonia Valdense",
        "Colonia Suiza",
        "Florencio Sánchez",
        "Conchillas",
      ],
    },
    {
      Estado: "Durazno",
      Ciudades: [
        "Durazno",
        "Sarandí del Yí",
        "Villa del Carmen",
        "Blanquillo",
        "Carmen",
        "Centenario",
        "Carlos Reyles",
        "La Paloma",
        "San Jorge",
        "Aguas Buenas",
      ],
    },
    {
      Estado: "Flores",
      Ciudades: [
        "Trinidad",
        "Ismael Cortinas",
        "Andresito",
        "Cerro Colorado",
        "La Casilla",
        "Grecco",
      ],
    },
    {
      Estado: "Florida",
      Ciudades: [
        "Florida",
        "Sarandí Grande",
        "25 de Agosto",
        "Casupá",
        "Fray Marcos",
        "Cardal",
        "Independencia",
        "Capilla del Sauce",
        "Goñi",
        "Reboledo",
        "Pintado",
        "Mendoza",
        "La Cruz",
        "Talita",
      ],
    },
    {
      Estado: "Lavalleja",
      Ciudades: [
        "Minas",
        "José Pedro Varela",
        "Solís de Mataojo",
        "Zapicán",
        "Villa del Rosario",
        "Colón",
        "Mariscala",
        "José Batlle y Ordóñez",
        "Joaquín Suárez",
        "Illescas",
        "Aramendía",
        "Polanco del Yí",
      ],
    },
    {
      Estado: "Maldonado",
      Ciudades: [
        "Maldonado",
        "Punta del Este",
        "San Carlos",
        "Piriápolis",
        "Aiguá",
        "Pan de Azúcar",
        "Solís",
        "José Ignacio",
        "Las Flores",
        "Garzón",
        "Manantiales",
        "Punta Ballena",
        "La Barra",
      ],
    },
    {
      Estado: "Montevideo",
      Ciudades: [
        "Montevideo",
        "Ciudad Vieja",
        "Punta Carretas",
        "Pocitos",
        "Buceo",
        "Malvín",
        "Carrasco",
        "Prado",
      ],
    },
    {
      Estado: "Paysandú",
      Ciudades: [
        "Paysandú",
        "Guichón",
        "Quebracho",
        "Porvenir",
        "Piedras Coloradas",
        "Tambores",
        "Lorenzo Geyres",
        "Esperanza",
        "Chapicuy",
        "Constancia",
        "Orgoroso",
      ],
    },
    {
      Estado: "Río Negro",
      Ciudades: [
        "Fray Bentos",
        "Young",
        "Nuevo Berlín",
        "San Javier",
        "Menafra",
        "Grecco",
        "Las Cañas",
        "Paso de los Mellizos",
        "Tres Quintas",
        "Sauce",
        "El Ombú",
        "Sarandí de Navarro",
      ],
    },
    {
      Estado: "Rivera",
      Ciudades: [
        "Rivera",
        "Tranqueras",
        "Vichadero",
        "Minas de Corrales",
        "Mandubí",
        "Lagunón",
        "Pajonal",
        "Masoller",
        "Cerros Blancos",
        "Las Flores",
      ],
    },
    {
      Estado: "Rocha",
      Ciudades: [
        "Rocha",
        "Chuy",
        "Lascano",
        "Castillos",
        "La Paloma",
        "Cebollatí",
        "Velázquez",
        "19 de Abril",
        "La Coronilla",
        "Barra del Chuy",
        "Aguas Dulces",
        "Punta del Diablo",
        "San Luis Al Medio",
        "San Miguel",
      ],
    },
    {
      Estado: "Salto",
      Ciudades: [
        "Salto",
        "Bella Unión",
        "Constitución",
        "Belén",
        "Daymán",
        "San Antonio",
        "Campo de Todos",
        "Rincón de Valentín",
        "Pueblo Fernández",
        "Pueblo Lavalleja",
      ],
    },
    {
      Estado: "San José",
      Ciudades: [
        "San José de Mayo",
        "Libertad",
        "Ciudad del Plata",
        "Rodríguez",
        "Ecilda Paullier",
        "Rafael Perazza",
        "Santa Lucía",
        "Cañada Grande",
        "Puntas de Valdez",
        "Ituzaingó",
        "Kiyú",
        "Scavino",
      ],
    },
    {
      Estado: "Soriano",
      Ciudades: [
        "Mercedes",
        "Dolores",
        "Cardona",
        "José Enrique Rodó",
        "Palmitas",
        "Egaña",
        "Risso",
        "Villa Soriano",
        "Santa Catalina",
        "Cañada Nieto",
        "Perseverano",
        "La Loma",
        "Paraje La Concordia",
      ],
    },
    {
      Estado: "Tacuarembó",
      Ciudades: [
        "Tacuarembó",
        "Paso de los Toros",
        "San Gregorio de Polanco",
        "Achar",
        "Las Toscas",
        "Curtina",
        "Cuchilla de Peralta",
        "Tambores",
        "Villa Ansina",
      ],
    },
    {
      Estado: "Treinta y Tres",
      Ciudades: [
        "Treinta y Tres",
        "Vergara",
        "Santa Clara de Olimar",
        "Cebollatí",
        "Rincón",
        "General Enrique Martínez",
        "María Albina",
        "Villa Sara",
        "Margarita",
        "Ramón Trigo",
        "Puntas del Parao",
      ],
    },
  ];
  
  export default uruguay_cities;