const NavbarTranslator = {
    spanish: {
        news: "Noticias",
        directory: "Directorio",
        register_p: "Registrar Proyecto",
        explore: "Explorar proyectos",
        alliance: "Alianza juvenil e infantil",
        conscience: "Con ConCiencia",
        aboutUs: "Acerca de nosotros",
        me: "Yo",
        profile: "Mi perfil",
        project: "Mis proyectos",
        support: "Soporte",
        logOut: "Cerrar sesión",
        participate: "¡Participa!",
        login: "Iniciar sesión",
        register:"Crear cuenta",
    },
    english: {
        news: "News",
        directory: "Directory",
        register_p: "Register project",
        explore: "Explore projects",
        alliance: "Youth and children's alliance",
        conscience: "With ConScience",
        aboutUs: "About us",
        me: "Me",
        profile: "My profile",
        project: "My project",
        support: "Support",
        logOut: "Log out",
        participate: "¡Participate!",
        login: "Sign in",
        register:"Create account",
    },
};

export default NavbarTranslator;